/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graficar.angulos;

import java.awt.Color;
import java.awt.Graphics;
import javax.swing.JOptionPane;

/**
 *
 * @author Erick Muke
 */
public class Angulos extends javax.swing.JApplet {

    /**
     * Initializes the applet Angulos
     */
    @Override
    public void init() {
        //Cambiar las dimensiones de Applet
        resize(350, 500);
        //Color blanco
        this.getContentPane().setBackground(Color.white);
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Angulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Angulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Angulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Angulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the applet */
 /* Create and display the applet */
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    //Variables
    int num1, num2, num3 = 0;
    String funciones;
    double punto, y = 0, x = 0;

    //Metodo para graficar 
    public void Graficar() {

        //Condicion que evalua el textField
        if (texto.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Ingrese un angulo positivo");
            texto.requestFocus();
        } else {
            //Pasamos el dato a tipo int
            num1 = Integer.parseInt(texto.getText());
        }
//Mandamos a llamar el metodo getGraphics

        Graphics p = getGraphics();
        p.setColor(new Color(255, 255, 255));//Color blanco
        //x y ancho y alto
        p.fillRect(0, 100, 300, 400);//Fondo para que borre las anteriores 
        p.setColor(new Color(0, 0, 0));//Color para las lineas
        p.drawLine(50, 300, 300, 300);//Eje horizontal(x)
        p.drawLine(150, 100, 150, 350);//Eje vertical(y)
        //Metodo que le de color a la linea del angulo
        p.setColor(new Color(255, 0, 0));
        //Ciclo for que grafique el angulo
        //Linea vertical
        for (int i = 50; i < 300; i += 8) {
            //Graficando los puntos de los ejes
            p.drawLine(i, 300, i, 304);
        }
        //Linea Horizontal
        for (int j = 120; j < 350; j += 8) {
            //Graficando los puntos de los ejes
            p.drawLine(145, j, 155, j);
        }

        for (double x = num1; x < num2; x += 0.01) {
            punto =  x ;

            switch (funciones) {
                //angulo
                case "Angulo":
                    y = Math.tanh(x);
                    break;
            }

        }
    }
}


/**
 * This method is called from within the init() method to initialize the form.
 * WARNING: Do NOT modify this code. The content of this method is always
 * regenerated by the Form Editor.
 */
@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Caja = new javax.swing.JComboBox<>();
        texto = new javax.swing.JTextField();
        Graficar = new javax.swing.JButton();

        Caja.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Angulos" }));

        texto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoActionPerformed(evt);
            }
        });

        Graficar.setText("Graficar");
        Graficar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GraficarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Graficar)
                .addGap(21, 21, 21)
                .addComponent(texto, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Caja, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(539, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Graficar)
                    .addComponent(texto, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Caja, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void GraficarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GraficarActionPerformed
        // TODO add your handling code here:
      Graficar();
    }//GEN-LAST:event_GraficarActionPerformed

    private void textoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Caja;
    private javax.swing.JButton Graficar;
    private javax.swing.JTextField texto;
    // End of variables declaration//GEN-END:variables
}
