/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quimica;

/**
 *
 * @author jose_
 */
public class Rex extends javax.swing.JFrame {

    /**
     * Creates new form Rex
     */
    public Rex() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setBackground(new java.awt.Color(0, 153, 153));
        jTextArea1.setColumns(20);
        jTextArea1.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea1.setRows(5);
        jTextArea1.setText("¿Que es?\n\nLas reacciones de oxidación-reducción forman una parte importante del mundo que nos rodea. Abarcan desde la combustión de combustibles fósiles hasta la acción de los blanqueadores de ropa domésticos. Asimismo, la mayoría de los elementos metálicos y no metálicos se obtienen de sus minerales por procesos de oxidación o de reducción. Hay muchos fenómenos que se dan a tu alrededor y en tu propio cuerpo relacionados con la química de los procesos de oxidación y reducción.\n\n\n\n\n¿Por qué tenemos que equilibrar la reacción química?\n\nLa ecuación química equilibrada describe exactamente las cantidades de los reactantes y productos en una reacción química.Para que una ecuación esté equilibrada, las sumas de las cargas eléctricas en ambos lados tienen que ser idénticas.\n\n\n\n\nInstrucciones para equilibrar las ecuaciones redox\n\nPaso 1. Se escribe una reacción desequilibrada\nPaso 2. Se desmonta la reacción redox a las reacciones parciales\na) Se determinan los números de la oxidación de cada átomo respectivo.\nb) Se identifican los pares redox en la reacción\nc) Se combinan los pares redox en dos reacciones parciales\nPaso 3. Se equilibran los átomos en las ecuaciones parciales\na) Se equilibran todos los átomos excepto del H y del O\nb) Se equilibran las cargas añadiendo H+ o OH-\nb) Se equilibran los átomos del oxígeno añadiendo H2O\nPaso 4: Se iguala el número de los electrones perdidos y recibidos en las reacciones parciales\nPaso 5: Se suman las ecuaciones parciales\nPaso 6: Se acorta la ecuación\nY al final, siempre se verifica el equilibrio de las cargas y de los elementos");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 667, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Rex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Rex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Rex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Rex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Rex().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
